base_url = "https://msn.qzz.io/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "Lengyu's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/top/", name = "Top"},
    {url = "$BASE_URL/issue-2/", name = "About"},
    {url = "$BASE_URL/issue-3/", name = "Friends"},
]
[markdown]
highlight_code = true
render_emoji = true
